yt/urls.py
from django.urls import path

from .views import ( 
                     ytview,result,playlist,playlist_details,
                     result_comments,result_likes,searchresults,
                     result_dates
                     )       

app_name='yt'

urlpatterns = [
    path('',ytview,name='yt'),
    path('yt/results_views',result,name='result-views'),
    path('yt/results_comments',result_comments,name='result-comments'),
    path('yt/results_likes',result_likes,name='result-likes'),
    path('yt/results_dates',result_dates,name='result-dates'),
    path('yt/playlist',playlist,name='playlist'),
    path('yt/playlistdetail',playlist_details,name='playlistdetail'),
    path('yt/serchresults',searchresults,name='searchresults'),
]
    

ytcontent/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('yt.urls'),name='yt' )
]


yt/models.py
from django.db import models

# Create your models here.

yt/forms.py
from django import forms
from django.core.validators import RegexValidator

#channel_id=RegexValidator(r'(\S{24})',message='please use the serach bar to find the reuqired channel ID.')
                           #please use the serach bar to find the reuqired channel ID')
#validators=[channel_id]
class Fooform(forms.Form):
    #username = forms.CharField(required=False)
    channelname=forms.CharField(        
        required=True,min_length=24,widget= forms.TextInput(attrs={'placeholder':'Please enter the 24 character Channel ID'}))
     
                           
    
# class PlayListForm(forms.Form):
#     pass
    
    
# class ChannelIdForm(forms.Form):
#     keyword=forms.CharField(required=True)

yt/views.py
from django.http import HttpResponse
from django.shortcuts import render
import os
from googleapiclient.discovery import build
from .forms import Fooform
#from .helper import youtube_api,youtube,get_channel_stats,get_video_ids,get_video_details
from .mixin import Youtube
from datetime import datetime


# Create your views here.
details=Youtube()

def ytview(request):

    form = Fooform(request.POST,None)
    
    
    context={"form":form}

    return render(request, "yt/index.html",context)

def result(request):
    form = Fooform(request.POST,None)
     
    channelname=request.POST.get("channelname")
      
    channel_stats=details.get_channel_stats(channelname)
    channel_id=channel_stats[0]['playlist_id']
    video_ids=details.get_video_ids(channel_id)
    video_details=details.get_video_details(video_ids)
    videos=video_details[0]
    total_time=video_details[1]
    print(total_time)
    videos.sort(key=lambda vid:vid['Views'],reverse=True)
    toptenvideo=[]
    for video in videos[:40]:
        video['Published_date']=video['Published_date'].split('T')[0]
        toptenvideo.append(video)
    context={'videos':video_details,"videos":videos,"video_ids":video_ids,"toptenvideo":toptenvideo,"channel_stats":channel_stats,"channelname":channelname,"total_time": total_time}
    return render(request, "yt/result_views.html",context)

def result_comments(request):
    form = Fooform(request.POST,None)
    channelname=request.POST.get("channelname")

    channel_stats=details.get_channel_stats(channelname)
    channel_id=channel_stats[0]['playlist_id']
    video_ids=details.get_video_ids(channel_id)
    video_details=details.get_video_details(video_ids)
    videos=video_details[0]
    total_time=video_details[1]
    print(total_time)
    videos.sort(key=lambda vid:vid['Comments'],reverse=True)
    toptenvideo=[]
    for video in videos[:40]:
        video['Published_date']=video['Published_date'].split('T')[0]
        toptenvideo.append(video)
    context={'videos':video_details,"videos":videos,"video_ids":video_ids,"toptenvideo":toptenvideo,"channel_stats":channel_stats,"channelname":channelname,"total_time": total_time}
    return render(request, "yt/result_comments.html",context)

def result_likes(request):
    form = Fooform(request.POST,None)
    
    channelname=request.POST.get("channelname")
       
    channel_stats=details.get_channel_stats(channelname)
    channel_id=channel_stats[0]['playlist_id']
    video_ids=details.get_video_ids(channel_id)
    video_details=details.get_video_details(video_ids)
    videos=video_details[0]
    total_time=video_details[1]
    print(total_time)
    videos.sort(key=lambda vid:vid['Likes'],reverse=True)
    toptenvideo=[]
    for video in videos[:40]:
        video['Published_date']=video['Published_date'].split('T')[0]
        toptenvideo.append(video)
    context={'videos':video_details,"videos":videos,"video_ids":video_ids,"toptenvideo":toptenvideo,"channel_stats":channel_stats,"channelname":channelname,"total_time": total_time}
    return render(request, "yt/result_likes.html",context)

def result_dates(request):
    form = Fooform(request.POST,None)
     
    channelname=request.POST.get("channelname")
       
    channel_stats=details.get_channel_stats(channelname)
    channel_id=channel_stats[0]['playlist_id']
    video_ids=details.get_video_ids(channel_id)
    video_details=details.get_video_details(video_ids)
    videos=video_details[0]
    total_time=video_details[1]
    print(total_time)
    videos.sort(key=lambda vid:vid['Published_date'],reverse=True)
    toptenvideo=[]
    for video in videos[:12]:  
        video['Published_date']=video['Published_date'].split('T')[0]      
        toptenvideo.append(video)
    context={'videos':video_details,"videos":videos,"video_ids":video_ids,"toptenvideo":toptenvideo,"channel_stats":channel_stats,"channelname":channelname,"total_time": total_time}
    return render(request, "yt/result_dates.html",context)

def playlist(request):
    
    
    # username = request.POST.get("username")
    channelname=request.POST.get("channelname")
    
    playlist=details.get_playlists(channelname)
    
    context={'channelname':channelname,"playlist":playlist}
    return render(request, "yt/playlist.html",context)
    

def playlist_details (request):
        
          
        playlist_id=request.GET.get('playlist_id')
        print(playlist_id)
        vid_details=details.get_video_ids(playlist_id)
        get_vid_details=details.get_video_details(vid_details)
        videos=get_vid_details[0]
        total_time=get_vid_details[1]
        videos.sort(key=lambda vid:vid['Views'],reverse=True)
        for video in videos:  
            video['Published_date']=video['Published_date'].split('T')[0]

        context={"hello":"hello","videos":videos,"total_time":total_time}
        return render(request, "yt/playlistdetail.html",context)

def searchresults(request):
    
    keyword= request.GET.get("keyword")
    results=details.search(keyword)
    
    context={"results":results}
    print(keyword)
    return render(request, "yt/serchresults.html",context)





yt/templates/yt/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
  
    
   
            

    <title>Document</title>
</head>
<body>
    {% include 'yt/navbar.html' %}
    <div class= "container pt-3 pb-3">
    

    {% block content %}
    
    
    {% endblock %}


</div>
</body>
</html>   

yt/templates/yt/index.html
{% extends "yt/base.html" %}
{% load crispy_forms_tags %}


{% block content %}

    <h4>Please Enter the Channel Name</h4>
    <div class="form-group row">
        <div class="col-sm-10">
    <form action="{% url 'yt:result-views' %}" method="POST">

        {% csrf_token %}

        {{ form|crispy }}
   
        <div style="display: flex; flex-wrap: wrap ;">

        <button type="submit" class="btn btn-primary mb-2 ml-3" style="width: 170px;">Summary_Views</button>
        <button type="submit" formaction="{% url 'yt:result-comments' %}" class="btn btn-primary mb-2 ml-3 " style="width: 170px;">Summary_Comments</button>
        <button type="submit" formaction="{% url 'yt:result-likes' %}" class="btn btn-primary mb-2 ml-3" style="width: 170px;">Summary_Likes</button>
        <button type="submit" formaction="{% url 'yt:result-dates' %}" class="btn btn-primary mb-2 ml-3" style="width: 170px;">Summary_Dates</button>
        <button type="submit" formaction="{% url 'yt:playlist' %}" class="btn btn-primary mb-2 ml-3" style="width: 170px;">Playlist_details</button>
    </div>   
    
</form>



</div>
</div>


{% endblock %}

yt/templates/yt/navbar.html

{% load crispy_forms_tags %}




    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="#"><h5>YT-Anlytics</h5></a>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="/"><h6>Home</h6> <span class="sr-only">(current)</span></a>
        </li>
        
      </ul>
      <form action="{% url 'yt:searchresults' %}" method="GET" class="form-inline my-2 my-lg-0" >
        {% csrf_token %}

          
       {% comment %}
       {{ form1.non_field_errors }}  
       {{ form1.keyword.errors }} 
       {{form1.keyword}}
       {% endcomment %}  
        
        
       <input class="form-control mr-sm-2" name="keyword" type="search" placeholder="Search for channel ID" aria-label="Search">
          <button class="btn btn-secondary mr-4 pl-4 pr-4 ml-4" type="submit">Search</button>
       

     
        
        
      </form>
    </div>
  </nav>

  


yt/templates/yt/playlist.html
{% extends "yt/base.html" %}
{% load crispy_forms_tags %}


{% block content %}

<style>
  .btn {
    width:300px;
    padding:5px;
}
</style>
<h4>List of Playlists</h4><h6>
  <br>(Click on Playlist ID - blue button below to get the details)</h6>


    <table id="simpleTable" class="table table-striped table-responsive ">
      <thead>
        <tr>
          <th scope="col">Playlist</th>
          <th scope="col">Playlist_id</th>
          <th scope="col">Description</th>

                    
        </tr>
      </thead>
      <tbody>

        {% for list in playlist  %}
    <tr>

        <td>
          <iframe width="150" height="150" src="https://www.youtube.com/embed/videoseries?list={{list.playlist_id}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media;
           gyroscope; picture-in-picture" allowfullscreen></iframe>

        </td>


        <td>
            <form method='GET' action="{% url 'yt:playlistdetail' %}" >
                {% csrf_token %}
                <input type='submit' name='playlist_id' value="{{list.playlist_id}}"  class="btn btn-primary mb-2" >
               

            </form>

            </td>

          <td>{{list.description}}</td> 
    
    {% endfor %}

        </tr>
        
      </tbody>
    </table>
    </div>  
    </div>



{% endblock %}

yt/templates/yt/playlistdetail.html
{% extends "yt/base.html" %}
{% load crispy_forms_tags %}


  

{% block content %}

    <h3 >Duration of the playlist : {{total_time}}</h3>

      <table id="simpleTable" class="table table-striped ">
        <thead>
          <tr>
            <th scope="col">Video</th>
            <!--th scope="col">Link</th-->
            <th scope="col">Title</th>
            <th scope="col">Duration</th>
            <th scope="col">Published_date </th>
            <th scope="col">Views</th>
            <th scope="col">Likes</th>
            <th scope="col">Comments</th>

            
          </tr>
        </thead>
        <tbody>

            {% for vid  in videos  %}
      <tr>
        <td><iframe width="150" height="100" src="https://www.youtube.com/embed/{{vid.link}}" 
          title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
           allowfullscreen></iframe></td>
          
          
          
        <td>{{vid.Title}}</td>
        <td>{{vid.Duration}}</td>
        <td>{{vid.Published_date}}</td>
        <td>{{vid.Views}}</td>
        <td>{{vid.Likes }}</td>
        <td>{{vid.Comments}}</td>

      {% endfor %}
  
          </tr>
          
        </tbody>
      </table>



</div>


{% endblock %}

yt/templates/yt/result_comments.html
{% extends "yt/base.html" %}
% load crispy_forms_tags %}

<style>

#btnSearch,
#btnClear{
    display: inline-block;
    vertical-align: top;
}
</style>

{% block content %}

    <h2 class="text-center pt-5">Channel Summary </h2>

    
{% comment %}

  
{% for r in detail.items %}
   ViewCount= {{r.statistics.viewCount}}
    SubscriberCount={{r.statistics.subscriberCount}}
    VideoCount={{r.statistics.videoCount}}
    
    {% endcomment %}

    
   

      <h2>Total Content Duration: {{total_time}}</h2>

      
      <table id="simpleTable" class="table table-striped ">
        <thead>
          <tr>
            
            <th scope="col">Channel_name</th>
            <th scope="col">Views </th>
            <th scope="col">Total_videos</th>
            <th scope="col">Subscribers</th>
            
          </tr>
        </thead>
        <tbody>

      {% for chan in channel_stats %}
      <tr>

        <td>{{chan.Channel_name}}</td>
            <td>{{chan.Views}}</td>
      <td>{{chan.Total_videos}}</td>
      <td>{{chan.Subscribers}}</td>
      {% endfor %}
  
          </tr>
          
        </tbody>
      </table>

    <h2 class="text-center pb-4">Top Videos-By Comments </h2>
  

    
    <div class="container ">
      <div class="row">
        {% for vid in toptenvideo %} 
          <div class="col col-md-3 col-sm-6 pb-4 ">


            
              <div class="card shadow-lg bg-white rounded">
                  <div class="card-block ">
                    
                    <iframe width="247" height="150" src="https://www.youtube.com/embed/{{vid.link}}" 
            title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
             allowfullscreen></iframe>
                    
                    <div class="card-title text-center">
                      <h6>{{vid.Title}}</h6>
                    </div>
                                        
                    <div class="card-text pl-2">Published Date:-{{vid.Published_date}}</div>
                      <div class="card-text pl-2">Total Views:- {{vid.Views}}</div>
                        <div class="card-text pl-2">Likes:-{{vid.Likes}}</div>
                          <div class="card-text pl-2">Comments:-{{vid.Comments}}</div>





                    <!--a style="margin-top: 10px;" href="#" class="btn btn-success">Click here</a-->
                  </div>
                </div>
                
            </div>
            {% endfor %}
            
           
      </div>
     </div>



      <script>
      $('simpleTable').tablesort();
          </script>
    
{% endblock %}

yt/templates/yt/result_dates.html
{% extends "yt/base.html" %}
% load crispy_forms_tags %}

<style>

#btnSearch,
#btnClear{
    display: inline-block;
    vertical-align: top;
}
</style>

{% block content %}

    <h2 class="text-center pt-5">Channel Summary </h2>

    
{% comment %}

  
{% for r in detail.items %}
   ViewCount= {{r.statistics.viewCount}}
    SubscriberCount={{r.statistics.subscriberCount}}
    VideoCount={{r.statistics.videoCount}}
    
    {% endcomment %}

    
   

      <h2>Total Content Duration: {{total_time}}</h2>

      
      <table id="simpleTable" class="table table-striped ">
        <thead>
          <tr>
            
            <th scope="col">Channel_name</th>
             <th scope="col">Views </th>
            <th scope="col">Total_videos</th>
            <th scope="col">Subscribers</th>
            
          </tr>
        </thead>
        <tbody>

      {% for chan in channel_stats %}
      <tr>

        <td>{{chan.Channel_name}}</td>
          <td>{{chan.Views}}</td>
      <td>{{chan.Total_videos}}</td>
      <td>{{chan.Subscribers}}</td>
      {% endfor %}
  
          </tr>
          
        </tbody>
      </table>

    <h2 class="text-center pb-4">Latest Videos </h2>
    <div class="row  pb-4">
      
  </div>

    
    <div class="container ">
      <div class="row">
        {% for vid in toptenvideo %} 
          <div class="col col-md-3 col-sm-6 pb-4 ">
              <div class="card shadow-lg bg-white rounded">
                  <div class="card-block ">
                    
                    <iframe width="247" height="150" src="https://www.youtube.com/embed/{{vid.link}}" 
            title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
             allowfullscreen></iframe>
                    
                    <div class="card-title text-center">
                      <h6>{{vid.Title}}</h6>
                    </div>
                                        
                    <div class="card-text pl-2">Published Date:-{{vid.Published_date}}</div>
                      <div class="card-text pl-2">Total Views:- {{vid.Views}}</div>
                        <div class="card-text pl-2">Likes:-{{vid.Likes}}</div>
                          <div class="card-text pl-2">Comments:-{{vid.Comments}}</div>





                    <!--a style="margin-top: 10px;" href="#" class="btn btn-success">Click here</a-->
                  </div>
                </div>
                
            </div>
            {% endfor %}
            
           
      </div>
     </div>



      <script>
      $('simpleTable').tablesort();
          </script>
    
{% endblock %}

yt/templates/yt/result_likes.html
{% extends "yt/base.html" %}
% load crispy_forms_tags %}

<style>

#btnSearch,
#btnClear{
    display: inline-block;
    vertical-align: top;
}
</style>

{% block content %}

    <h2 class="text-center pt-5">Channel Summary </h2>

    
{% comment %}

  
{% for r in detail.items %}
   ViewCount= {{r.statistics.viewCount}}
    SubscriberCount={{r.statistics.subscriberCount}}
    VideoCount={{r.statistics.videoCount}}
    
    {% endcomment %}

    
   

      <h2>Total Content Duration: {{total_time}}</h2>

      
      <table id="simpleTable" class="table table-striped ">
        <thead>
          <tr>
            
            <th scope="col">Channel_name</th>
            <th scope="col">Views </th>
            <th scope="col">Total_videos</th>
            <th scope="col">Subscribers</th>
            
          </tr>
        </thead>
        <tbody>

      {% for chan in channel_stats %}
      <tr>

        <td>{{chan.Channel_name}}</td>
          <td>{{chan.Views}}</td>
      <td>{{chan.Total_videos}}</td>
      <td>{{chan.Subscribers}}</td>
      {% endfor %}
  
          </tr>
          
        </tbody>
      </table>

    <h2 class="text-center pb-4">Top Videos-By Likes </h2>
    <div class="row  pb-4">
      
  </div>

    
    <div class="container ">
      <div class="row">
        {% for vid in toptenvideo %} 
          <div class="col col-md-3 col-sm-6 pb-4 ">


            
              <div class="card shadow-lg bg-white rounded">
                  <div class="card-block ">
                    
                    <iframe width="247" height="150" src="https://www.youtube.com/embed/{{vid.link}}" 
            title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
             allowfullscreen></iframe>
                    
                    <div class="card-title text-center">
                      <h6>{{vid.Title}}</h6>
                    </div>
                                        
                    <div class="card-text pl-2">Published Date:-{{vid.Published_date}}</div>
                      <div class="card-text pl-2">Total Views:- {{vid.Views}}</div>
                        <div class="card-text pl-2">Likes:-{{vid.Likes}}</div>
                          <div class="card-text pl-2">Comments:-{{vid.Comments}}</div>





                    <!--a style="margin-top: 10px;" href="#" class="btn btn-success">Click here</a-->
                  </div>
                </div>
                
            </div>
            {% endfor %}
            
           
      </div>
     </div>



      <script>
      $('simpleTable').tablesort();
          </script>
    
{% endblock %}

yt/templates/yt/result_views.html
{% extends "yt/base.html" %}
% load crispy_forms_tags %}

<style>

#btnSearch,
#btnClear{
    display: inline-block;
    vertical-align: top;
}
</style>

{% block content %}

    <h2 class="text-center pt-5">Channel Summary </h2>

    
{% comment %}

  
{% for r in detail.items %}
   ViewCount= {{r.statistics.viewCount}}
    SubscriberCount={{r.statistics.subscriberCount}}
    VideoCount={{r.statistics.videoCount}}
    
    {% endcomment %}

    
   

      <h2>Total Content Duration: {{total_time}}</h2>

      
      <table id="simpleTable" class="table table-striped ">
        <thead>
          <tr>
            
            <th scope="col">Channel_name</th>
            <th scope="col">Views </th>
            <th scope="col">Total_videos</th>
            <th scope="col">Subscribers</th>
            
          </tr>
        </thead>
        <tbody>

      {% for chan in channel_stats %}
      <tr>

        <td>{{chan.Channel_name}}</td>
           <td>{{chan.Views}}</td>
      <td>{{chan.Total_videos}}</td>
      <td>{{chan.Subscribers}}</td>
      {% endfor %}
  
          </tr>
          
        </tbody>
      </table>

    <h2 class="text-center pb-4">Top Videos-By Views </h2>
 

    
    <div class="container ">
      <div class="row">
        {% for vid in toptenvideo %} 
          <div class="col col-md-3 col-sm-6 pb-4 ">


            
              <div class="card shadow-lg bg-white rounded">
                  <div class="card-block ">
                    
                    <iframe width="247" height="150" src="https://www.youtube.com/embed/{{vid.link}}" 
            title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
             allowfullscreen></iframe>
                    
                    <div class="card-title text-center">
                      <h6>{{vid.Title}}</h6>
                    </div>
                                        
                    <div class="card-text pl-2">Published Date:-{{vid.Published_date}}</div>
                      <div class="card-text pl-2">Total Views:- {{vid.Views}}</div>
                        <div class="card-text pl-2">Likes:-{{vid.Likes}}</div>
                          <div class="card-text pl-2">Comments:-{{vid.Comments}}</div>





                    <!--a style="margin-top: 10px;" href="#" class="btn btn-success">Click here</a-->
                  </div>
                </div>
                
            </div>
            {% endfor %}
            
           
      </div>
     </div>



      <script>
      $('simpleTable').tablesort();
          </script>
    
{% endblock %}

yt/templates/yt/serchresults.html
{% extends "yt/base.html" %}
% load crispy_forms_tags %}

{% block content %}




<table id="simpleTable" class="table table-striped ">
    <thead>
      <tr>
        
        <th scope="col">Channel_name</th>
        <th scope="col">Subscribers</th>
        <th scope="col">Channel_Link</th>
               
      </tr>
    </thead>
    <tbody>

        {% for result in results.result  %}
  <tr>
     

    <td>{{result.id}}</td>
  <td>{{result.title}}</td> 
  <td><a href="https://www.youtube.com/channel/{{result.id}}">Channel</a></td>
  
  {% endfor %}

      </tr>
      
    </tbody>
  </table>


{% endblock%}